name: Build APK Definitiva
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    # Usamos una "máquina dentro de la máquina" que ya tiene todo configurado
    container:
      image: beevelop/cordova:latest

    steps:
      - uses: actions/checkout@v4

      - name: Aceptar Licencias de Android
        run: |
          mkdir -p /opt/android-sdk/licenses
          echo "24333f8a63b6825ea9c5573f83c2eb295f224713" > /opt/android-sdk/licenses/android-sdk-license
          echo "84831b9409646a918e30573bab4c9c91346d8abd" > /opt/android-sdk/licenses/android-sdk-preview-license

      - name: Construir Proyecto
        run: |
          cordova platform add android@10.1.2
          cordova build android --debug --device -- --gradleArg=-Pandroid.useAndroidX=true --gradleArg=-Pandroid.enableJetifier=true

      - name: Subir APK Resultante
        uses: actions/upload-artifact@v4
        with:
          name: MiJuego-Final-APK
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
