name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar Gradle compatible
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '7.6' # <--- Versión mágica que tiene XmlParser

      - name: Build APK
        run: |
          npm install -g cordova@11.0.0
          cordova platform add android@10.1.2
          
          # Forzamos a que el proyecto use Gradle 7.6 y no el 9 de GitHub
          mkdir -p platforms/android/gradle/wrapper
          echo "distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-all.zip" > platforms/android/gradle/wrapper/gradle-wrapper.properties
          
          # Ajustes para que no falle con las librerías modernas
          echo "android.useAndroidX=true" >> platforms/android/gradle.properties
          echo "android.enableJetifier=true" >> platforms/android/gradle.properties
          
          cordova build android --debug

      - name: Entregar APK
        uses: actions/upload-artifact@v4
        with:
          name: MiJuego-Final
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
