name: Build APK Final
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11' # La versión perfecta para Cordova 10

      - name: Construir Android con Action Oficial
        uses: ionelmc/cordova-build-action@v1
        with:
          platform: android
          # Esto fuerza a que use las librerías modernas de Android sin romper nada
          args: --debug --device -- --gradleArg=-Pandroid.useAndroidX=true --gradleArg=-Pandroid.enableJetifier=true

      - name: Descargar mi APK
        uses: actions/upload-artifact@v4
        with:
          name: MiJuego-Proyecto4
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
